version: "1"
services:
  gascontrol:
   build:
     context: ./gascontrol
   ports:
     - "9000:9000"
   privileged: true
   environment:
   - OPERATING_SYSTEM=mock
  react-frontend:
    build: ./my-react-frontend
    ports:
      - "3000:5000"  # Port 5000 is used by 'serve' in the Dockerfile
    depends_on:
      - gascontrol
